apiVersion: apps/v1
kind: Deployment
metadata:
  name: lite-scaler
spec:
  template:
    spec:
      nodeSelector:
        lite-scaler: "true"
      tolerations:
        - key: dedicated
          operator: Equal
          value: lite-scaler
          effect: NoSchedule
