apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ../../base

patches:
  - path: config-patch.yaml
    target:
      kind: ConfigMap
      name: lite-scaller-config
  - path: deployment-patch.yaml

images:
  - name: cr.yandex/crph9fp6537285vojlnc/lite-scaller
    newTag: latest
