apiVersion: apps/v1
kind: Deployment
metadata:
  name: lite-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lite-scaler
  template:
    metadata:
      labels:
        app: lite-scaler
    spec:
      containers:
        - name: lite-scaler
          image: cr.yandex/crph9fp6537285vojlnc/lite-scaller:latest
          env:
            - name: CONFIG_PATH
              value: /config/config.yaml
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: sa-key
              mountPath: /secrets
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: sa-key
          secret:
            secretName: lite-scaller-sa
        - name: config
          configMap:
            name: lite-scaller-config
