# Test application to show how to place pods on our self managed node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper-app
  namespace: default
  labels:
    tag: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sleeper-app
  template:
    metadata:
      labels:
        app: sleeper-app
        tag: demo
    spec:
      nodeSelector:
        workload: demo
      tolerations:
        - key: dedicated
          operator: Equal
          value: demo
          effect: NoSchedule
      containers:
        - name: sleeper
          image: cr.yandex/crpcvsde88m85as3hdu0/demo:latest
          resources:
            requests:
              cpu: "500m"
              memory: 256Mi
